pages/BF-DP/Portal/aduan/01/index.vue
pages/BF-DP/Portal/aduan/index.vue
pages/BF-DP/Portal/bantuan/01/index.vue
pages/BF-DP/Portal/bantuan/index.vue
pages/BF-DP/Portal/index.vue
pages/BF-DP/Portal/profile/01/index.vue
pages/BF-DP/Portal/profile/index.vue

Adds the Aduan page to the Status Tracking system, allowing users to navigate and view Aduan-related status.
Add simulation by role
https://ansisystems.sharepoint.com/:x:/r/sites/LZS-NAS/_layouts/15/Doc.aspx?sourcedoc=%7B1EED2480-2409-4E17-891C-6B81AFADFC06%7D&file=RTMF-LZS-NAS-DP-ST.xlsx&action=default&mobileredirect=true

Mockup: Status Tracking - Add Aduan 

---

components/RsTable.vue
navigation/index.js
pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/[id]/index.vue
pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/index.vue
pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/tambah/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bantuan-bulk-kelulusan/[id].vue
pages/BF-BTN/bantuan-bulk/senarai-bantuan-bulk-kelulusan/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bantuan-bulk-sokongan/[id].vue
pages/BF-BTN/bantuan-bulk/senarai-bantuan-bulk-sokongan/index.vue

feat(RsTable): per-column search, columnSearch helpers, combine globel+column filters, reset pagination, UI polish

Bulk Processing

---

navigation/index.js
pages/BF-TNI/laporan/laporan-baki-tabung-semasa/index.vue
pages/BF-TNI/laporan/serahan-bantuan-tunai/index.vue

Added two new report pages: 'Laporan Baki Tabung Semasa' and 'Laporan Serahan Bantuan Tunai' under /BF-TNI/laporan, including their navigation entries. Both pages include search/filter forms, data tables, and export functionality (CSV, PDF, Excel).

Add BF-TNI laporan pages and navigation entries

---

assets/js/formkit-custom.js
components/formkit/DateTimePicker.vue
navigation/index.js
package.json
pages/BF-PRF/KF/RUU/01_01/index.vue
pages/BF-PRF/KF/RUU/01_01/kemaskini/index.vue
pages/BF-PRF/KF/RUU/01_01/tambah_kategori/index.vue
pages/BF-PRF/KF/RUU/01_01/tambah_maklumat_kelulusan/index.vue
pages/BF-PRF/KF/RUU/01_02/01_02_lihat/index.vue
pages/BF-PRF/KF/RUU/02_01/index.vue
pages/BF-PRF/KF/RUU/02_01/kelulusan/index.vue
pages/BF-PRF/KF/RUU/02_01/lihat/index.vue

Add page Tambah/Kemaskini Maklumat Tambah/Kemaskini Maklumat Data (RUU)

[BF-PRF-KF-RUU]- Maklumat Kelulusan Data (RUU)

---

navigation/index.js
pages/BF-BTN/pelaporan/laporan-permohonan-bantuan/index.vue
pages/BF-BTN/pelaporan/laporan-status-siasatan-lapangan/index.vue
pages/BF-BTN/pelaporan/senarai-laporan/index.vue

Added three new report pages under BF-BTN/pelaporan: 'Laporan Permohonan Bantuan', 'Laporan Status Siasatan Lapangan', and 'Senarai Laporan'. Updated navigation to include a 'Pelaporan' section with a link to 'Senarai Laporan'. These pages provide search, filtering, and export features for report management.

[BF-BTN] Add pelaporan report pages and navigation

---

navigation/index.js
pages/BF-BTN/mohon-bantuan/index.vue
pages/BF-PRF/KF/RUU/01_01/index.vue
pages/BF-PRF/KF/RUU/01_01/tambah_kategori/index.vue
pages/BF-PRF/KF/RUU/01_02/01_02_lihat/index.vue

Add page for BF-BTN  and modify page BF-PRF-KF-RUU

Add page for BF-BTN  and modify page BF-PRF-KF-RUU

---

pages/BF-BTN/tugasan/bantuan/siasatan/siasatan-eoad/[id]/index.vue

Add Datatable in Tab profiling for pages BF-BTN\tugasan\bantuan\siasatan\siasatan-eoad\[id]

Modify page BF-BTN\tugasan\bantuan\siasatan\siasatan-eoad\[id]

---

pages/BF-PRF/AS/PA-1/index.vue

Tambah sub option pada keperluan_kategori
Tambah popup modal pada btn "Seterusnya"
Redirect page untuk new/existing user mengikut kategori

Enhance BF-PRF Penilaian Awal

---

pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/tambah/index.vue

- Expanded the list of Cawangan options to include various locations in Gombak, Hulu Langat, Kuala Selangor, Sabak Bernam, Petaling, Sepang, Kuala Langat, Hulu Selangor, and Klang.
- Enhanced user selection experience by providing more specific branch labels.

[BF-BTN] Update Cawangan options in aid application form

---

pages/BF-PRF/KF/PP/03_01/index.vue

- Removed debug information from the body template for cleaner production code.
- Updated action buttons to include tooltips for better user guidance on edit, view, and delete actions.
- Enhanced the layout of action buttons for improved user experience and accessibility.
- Introduced a new reactive state for managing tooltip visibility.

Refactor action buttons and add tooltips in the profiling component

---

pages/BF-BTN/tugasan/bantuan/kelulusan/Dialisis/[id]/index.vue

- Updated button variants for better visual consistency and user experience.
- Improved input fields with placeholders and added icons for date selection.
- Introduced new action handlers for saving and submitting dialysis assistance, enhancing functionality.
- Streamlined layout for better readability and usability in the assistance form.

[BF-BTN] Refactor dialysis assistance form and enhance UI components

---

navigation/index.js

…ement
- Consolidated child routes under "Senarai SLA" for better organization.
- Added new paths for "Senarai Permohonan Kelulusan SLA", "Butiran Permohonan Kelulusan SLA", and other related items.
- Improved readability by removing redundant code and restructuring the navigation hierarchy.

Refactor navigation structure for role access and configuration management

---

pages/BF-BTN/tugasan/bantuan/siasatan/[id]/index.vue

- Introduced a new field for selecting 'Kategori Penerima' with options for 'Organisasi', 'Syarikat', and 'Recipient'.
- Updated modal footer button to navigate to different pages based on the selected category.
- Added validation to ensure a category is selected before proceeding.
- Cleaned up the new registration state management for improved clarity and reset functionality.

[BF-BTN] Enhance new registration modal functionality

---

pages/BF-BTN/tugasan/bantuan/siasatan/siasatan-eoad-2/[id]/index.vue
pages/BF-BTN/tugasan/index.vue

- Modify Screen Layout
- Add accordion

Enhancement screen  BF-BTN\tugasan\bantuan\siasatan\siasatan-eoad-2

---

pages/BF-BTN/mohon-bantuan/index.vue
pages/BF-BTN/senarai-permintaan-pembelian/index.vue
pages/BF-BTN/tugasan/bantuan/siasatan/[id]/index.vue

- Updated document action buttons to conditionally trigger edit or upload functions based on document ID.
- Added a new document entry for "Senarai Permintaan Pembelian" with corresponding routing for editing.
- Introduced a new page for managing purchase requests, including item management and summary calculations.
- Enhanced user interface with structured sections for item details and action buttons.

Implement document handling and new page for purchase requests

---

pages/BF-BTN/senarai-permintaan-pembelian/index.vue

- Updated table column widths for better alignment and readability.
- Replaced the summary section with a more concise total cost display.
- Enhanced unit options with categorized headers for improved clarity.
- Updated predefined items list to reflect school uniform items with appropriate units and prices.
- Improved dropdown behavior to ensure options display correctly without overflow issues.

Refactor purchase request page layout and enhance unit options

---

navigation/index.js
pages/BF-PRF/KF/LK/01_02/index.vue
pages/BF-PRF/KF/LK/01_03/[id]/index.vue
pages/BF-PRF/KF/LK/01_03/index.vue
pages/BF-PRF/KF/LK/02_01/[id]/index.vue
pages/BF-PRF/KF/LK/02_01/index.vue
pages/BF-PRF/KF/LK/02_02/index.vue
pages/BF-PRF/KF/LK/02_03/index.vue

- Added index.vue for listing Level Kelulusan with table and actions.
- Created detail view (02_01) for displaying Level Kelulusan details.
- Developed approval form (02_03) for processing Level Kelulusan with validation and notifications.
- Integrated local storage for managing Level Kelulusan data.
- Enhanced breadcrumb navigation for better user experience.
- Implemented date formatting and status variant handling for UI consistency.

[BF-PRF]feat: Implement Level Kelulusan Management Pages

---

navigation/index.js
pages/BF-PRF/AS/pelaporan/asnaf/pengesahan-hospital/index.vue
pages/BF-PRF/AS/pelaporan/asnaf/pengesahan-sekolah-ipt/index.vue

Add organization details to hospital and school confirmation pages

BF-PRF/AS/pelaporan/asnaf/pengesahan-sekolah-ipt feat BF-PRF/AS/pelaporan/asnaf/pengesahan-hospital:

---

pages/BF-BTN/tugasan/bantuan/siasatan/[id]/draf-bq.vue

- Added 'Rujukan' and 'Jenis Kerja' fields to the form for better item tracking.
- Updated labels for 'Kuantiti' and 'Kadar (RM)' to improve clarity.
- Adjusted table headers and grid layout for improved readability.
- Enhanced the 'Keterangan Kerja' field placeholder for better user guidance.
- Updated the form data initialization to include new 'jenisKerja' options.

Enhance draf-bq.vue with new fields and layout adjustments

---

pages/BF-BTN/tugasan/bantuan/siasatan/[id]/draf-bq.vue
pages/BF-BTN/tugasan/index.vue

- Adjusted modal z-index in index.vue for better visibility.
- Updated applicant name in siasatanData to "Masjid At-Taqwa".
- Removed outdated entry from semakanData for cleaner data management.
- Renamed 'Alamat' to 'Alamat Tapak' in draf-bq.vue for clarity.
- Enhanced 'jenisKerjaData' with detailed descriptions and new options for construction tasks.
- Improved form data initialization with clearer descriptions for better user understanding.

Update index.vue and draf-bq.vue for improved UI and data handling

---

pages/BF-BTN/tugasan/bantuan/semakan/[id]/[bantuanId]/index.vue
pages/BF-BTN/tugasan/bantuan/semakan/[id]/index.vue
pages/BF-BTN/tugasan/index.vue

- Introduced new select fields for "Product Package" and "Entitlement Product" specific to Bantuan ID B134.
- Enhanced the UI to display entitlement products based on the selected package.
- Added new card sections for displaying entitlement product lists and investigation details for Bantuan B134.
- Updated mock data to include new entries for Bantuan B134 and related documents.
- Refactored document handling logic to support new document types and file uploads for LZS.

[BF-BTN](Semakan) feat: Add new form fields and data handling for Bantuan B134

---

pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/[id]/edit.vue
pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/[id]/index.vue
pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/index.vue
pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/tambah/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-kelulusan/[id].vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-kelulusan/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-semakan/[id].vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-semakan/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing/[id]/edit.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing/[id]/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing/tambah/index.vue

- Updated header sections across multiple components to include icons and descriptive subtitles for better clarity and user experience.
- Refactored action buttons in tables to use a consistent design and improved tooltip handling.
- Simplified the structure of various components, ensuring a more cohesive look and feel throughout the application.
- Removed unnecessary code and improved formatting for better readability.

[BF-BTN] Enhance UI consistency and improve component structure

---

pages/BF-BTN/tugasan/bantuan/siasatan/[id]/draf-bq.vue

- Improved the document preview section to support both HTML and PDF formats, adding appropriate iframe attributes for better security and functionality.
- Updated the document loading logic to use a specific Google Drive PDF for the first document while maintaining a sample HTML document for others.
- Removed unused document preview and text extraction functions to streamline the codebase.

Enhance document preview functionality and update loading logic

---

pages/BF-BTN/tuntutan-dengan-siasatan/mohon-tuntutan/asnaf/[id]/index.vue

- Refactor page: BF-BTN\tuntutan-dengan-siasatan\mohon-tuntutan\asnaf\[id]\index.vue

[BF-BTN] Refactor cipta invoice

---

pages/BF-BTN/tuntutan-dengan-siasatan/senarai-tuntutan/eoad/[id]/pengesahan.vue
pages/BF-BTN/tuntutan-dengan-siasatan/senarai-tuntutan/eoad/index.vue
pages/BF-BTN/tuntutan-dengan-siasatan/senarai-tuntutan/pelulus/[id]/semak-kelulusan.vue
pages/BF-BTN/tuntutan-dengan-siasatan/senarai-tuntutan/pelulus/index.vue

-Refactor page Pengesahan dan Pelulus in Senarai Tuntutan

[BF-BTN]-Refactor page Pengesahan dan Pelulus

---

pages/BF-BTN/tuntutan-dengan-siasatan/senarai-tuntutan/eoad/index.vue

Refactor page senarai tuntutan EOAD

[BF-BTN]-Refactor page senarai tuntutan EOAD

---

pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/[id]/edit.vue
pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/[id]/index.vue
pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/tambah/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-kelulusan/[id].vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-kelulusan/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-semakan/[id].vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing/[id]/edit.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing/[id]/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing/tambah/index.vue

- Removed unnecessary fields from the payment form, including Asnaf, Contributor, and Organization, to streamline user input.
- Updated the Mode of Payment section to use a radio button layout for better user experience.
- Enhanced file upload handling with improved validation and error messages for Excel file formats.
- Simplified the import process by updating the data structure and ensuring accurate calculations for total amounts.
- Improved UI elements for better clarity and interaction during the import process.

[BF-PRF/QS] [Faiz] Refactor payment form and import functionality

---

pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-kelulusan/[id].vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-semakan/[id].vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing/index.vue

- Added SLA information to the 'peringkatSemasa' field in multiple components.
- Introduced a new section for document uploads, allowing users to upload multiple files with clear instructions on accepted formats.
- Updated existing sections to improve clarity and organization of document-related information.

Update bantuan-bulk components to include SLA information and enhance document upload functionality

---

pages/BF-BTN/tuntutan-dengan-siasatan/senarai-tuntutan/eoad/index.vue

-Modify nama pemohon and nama bantuan

[BF-BTN] fix senarai tuntutan eoad

---

pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-kelulusan/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-semakan/index.vue

-remove peringkat semakan pada page semakan dan kelulusan

[BF-BTN]-Refactor Senarai Bulk Processing

---

pages/BF-BTN/bantuan-bulk/cipta-bantuan-bulk/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-kelulusan/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing-semakan/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing/[id]/index.vue
pages/BF-BTN/bantuan-bulk/senarai-bulk-processing/index.vue

- Updated the 'Status' label in the bantuan-bulk processing components for consistency.
- Introduced a reassign modal for bulk processing, allowing users to assign tasks to specific personnel.
- Enhanced the user interface by replacing icons and improving button functionalities.
- Removed unused code and commented-out sections for better readability.

Refactor bantuan-bulk components to improve user interaction and clarity

---

pages/BF-BTN/bantuan-pegawai/index.vue
pages/BF-BTN/bantuan/[id]/index.vue

[BF-BTN] Refactor aid information display and navigation
- Updated the layout of the aid information section for better readability and organization, introducing distinct subsections for "Maklumat Bantuan," "Status Bantuan," "Maklumat Kadar," and "Maklumat Penerima."
- Enhanced user navigation by implementing clickable elements for various identifiers (bantuan no, PA no, GL no, etc.) in the bantuan-pegawai page, allowing users to easily access related information.
- Added smooth scrolling functionality to the "Maklumat Bantuan" section when navigating from the bantuan-pegawai page.

[BF-BTN] Refactor aid information display and navigation

---

pages/BF-BTN/bantuan/index.vue
pages/BF-BTN/bantuan/pembatalan.vue

- Removed the "Batal" button from the aid review section to streamline the interface.
- Updated aid application identifiers to a new format (e.g., from "B005" to "NAS-2025-0001") for consistency.
- Introduced a new "Pembatalan" page for processing aid cancellations, featuring a tabbed interface for user input and confirmation.
- Added form fields for cancellation reasons and applicant information, enhancing the user experience during the cancellation process.

[BF-BTN] Implement cancellation feature for aid applications
